name: Bami Backend CI
run-name: ${{ github.actor }} 님이 안전한 merge을 위해 test를 하고 있습니다! 🚀

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download API key from private repository
      uses: actions/checkout@v2
      with:
        repository: ktb1-eight/api-key
        token: ${{ secrets.TOKEN_GITHUB }}
        path: api-key
        fetch-depth: 1 #최신 버전 커밋을 위해 ㅋ

    - name: Copy application-dev.yml
      run: |
        cp -f api-key/application-dev.yml src/main/resources/

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test
      shell: bash
